services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  StudioMitte\SentMails\:
    resource: '../Classes/*'

  StudioMitte\SentMails\EventListener\BeforeMailSentEventListener:
    tags:
      - name: event.listener
        identifier: 'mail-sent-beforemailsent'
        event: TYPO3\CMS\Core\Mail\Event\BeforeMailerSentMessageEvent

  StudioMitte\SentMails\EventListener\AfterMailSentEventListener:
    tags:
      - name: event.listener
        identifier: 'mail-sent-aftermailsent'
        event: TYPO3\CMS\Core\Mail\Event\AfterMailerSentMessageEvent
